### ISSUE TITLE
AI stuck before making move in Firefox

### ISSUE THREAD

**Issue by crackofdusk** [fasterthanlime/ld43#2]
Hey :wave: 

I encountered a bug while trying the game in Firefox: the AI never makes the first move.

## Steps to reproduce

1. Open https://fasterthanlime.itch.io/bamb
2. Start a new game
3. Make a move
4. Wait for AI to make a move
5. ???
6. Open the developer console and observe the error below

## Debugging information

```
TypeError: Argument 2 of DedicatedWorkerGlobalScope.postMessage can't be converted to a sequence.
```

The error references this line in `worker.js`:
```javascript
this.postMessage(msg, null);
```

Firefox version: 63.0.3

**Comment by crackofdusk** [comment]
Fixed by https://github.com/fasterthanlime/bamb/commit/a175bfe1f2ac1b4aa2a9153b9a539a60bd5f1b9f

**Comment by fasterthanlime** [comment]
Whew you already had this issue open when I made the fix, but I didn't even see it!

Thanks for the great report 👋
