### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by pablomayobre** [fasterthanlime/ld43#3]
Hey this game is great, and I found it really useful to look through it's code to make my own game, since I wanted to use a similar setup (Pixi.js + TypeScript then deploy to itch.io)

I wanted to know if there is some sort of license to this repo or if you can add one, so that I can properly credit you for the inspiration!

(Or scratch everything I did if I was not allowed to haha)

I imagine you also want to protect the rights to the game mechanic and the assets (aesthetic?) for the game so a LICENSE would help with that too

**Comment by fasterthanlime** [comment]
I usually just use MIT, I wonder what @velddev thinks, since we worked on this together.

**Comment by velddev** [comment]
I also usually use MIT when it comes to side-projects. So I completely agree with that license.

**Comment by fasterthanlime** [comment]
It is done :shipit:

**Comment by pablomayobre** [comment]
Nice! Super fast hahaha

Thanks to both of you ❤️
